User interface
enkog/Tic-Tac-Toe pull request #2
Opened 2020-09-30 08:59 UTC by emmanuellekamwa

In this second milestone, we have applied the basic flow of the game for user interaction

2020-09-30 15:14 UTC, bertil291utn requested changes
# **Status:** Changes requested 🟠 
<p align="center"> <img src="https://i.cubeupload.com/4HbSFK.jpg" alt="image" width="60" /> <br><strong>Not yet</strong> </p>

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

### Your work is amazing you master it GitHub Flow.

However, in order to accomplish all the requirements , you required to do these changes, listed below:

- [x] Edit pull request message following this [guideline](https://cdn.filestackcontent.com/osvFJEkQHWQsgDe0PJoQ)

Basic game flow is prepared: ([screenshot hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

* [x] `[REQUIRED]` game tells which player turn it is (without computing who the winner is)
* [x] `[REQUIRED]` game asks the player to select from available moves
* [x] `[REQUIRED]` game displays board after the player move (without computing which spots on the board are taken)
* [ ] `[REQUIRED]` game informs player if the selected move is a winning move (without computing the winning move)
* [ ] `[REQUIRED]` game informs player if the selected move is a draw move (without computing draw)
* [ ] `[REQUIRED]` game repeats all actions for the next player's move

- A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))
  - [ ] Add a loop to repeat the game, follow this example

```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move
  
  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```
### Summary
- Remember guys your code should not work yet, that's for the next milestone, for this one you could just add as inline comments or mocking up the methods. Example
```ruby
def validMove?(player)
  value=false
  value=true if player.move
value
end
```
-  Don't forget to work with inline comments below this comment box.

***

Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-09-30 15:14 UTC, bertil291utn commented on bin/main.rb
> +
## Used only in a class
- [ ] Remove `attr_accessor :player_one, :player_two, :board # Getter and Setter methods` because is only use with classes

2020-10-01 13:38 UTC, euqueme requested changes
> ### Pull Request reviewed by Maria Eugenia Queme P. (TSE)

### Hello @emmanuellekamwa and @enkog :balloon: :lollipop: 

### Thank you for working on the changes requested by the previous reviewer :medal_sports: :medal_sports: first of all claps to you for having a Readme file at this point :clap: :clap: :clap: I also see you are requesting for the player's names and this will make your game stand out a whole lot so please keep it! :video_game:  I can see from the messages in your code that you think well about your game logic, still the code it's breaking at some points and even though it doesn't have to work well in this milestone I still think you should fix a couple of things to make the logic make sense with clean code so please address them in the comments I've left in your code :construction: :construction_worker_woman: :construction_worker: 

### That's it, team! :raised_hands: 

### Please :pray:  do the changes :woman_technologist: :technologist: and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any questions? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

2020-10-01 13:38 UTC, euqueme commented on bin/main.rb
> +puts "#{player_one}, Choose a token: 'X' or 'O'"
- [ ] `player_one` is not defined, change it to `@player_one`

2020-10-01 13:38 UTC, euqueme commented on bin/main.rb
> +    puts "#{player_two}'s Token:  #{@assigned_tokens[:player_two]}"
- [ ] `player_one` is not defined, change it to `@player_one`
- [ ] `player_two` is not defined, change it to `@player_two`

2020-10-01 13:38 UTC, euqueme commented on bin/main.rb
> +puts 'Thanks for playing'
- [ ] These lines are part of the gameplay so they also should be put inside the loop

2020-10-01 13:38 UTC, euqueme commented on bin/main.rb
> +while selected_token == gets.chomp
- [ ] The while loop should depend on a boolean variable to terminate and not from an input request change it to something like the following:

```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move
  
  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```

2020-10-01 16:59 UTC, krys2fa commented on bin/main.rb
> +  else
- [ ] [REQUIRED] Please take another look at the implementation for checking for a valid token. It results in an endless loop when an invalid token is chosen as shown below.
<img width="597" alt="Screen Shot 2020-10-01 at 4 48 50 PM" src="https://user-images.githubusercontent.com/18187039/94840037-5870c600-0407-11eb-9176-c8087f74d6b4.png">

2020-10-01 17:06 UTC, krys2fa requested changes
Great job on implementing the requested changes @enkog and @emmanuellekamwa  👏

It's great that you have a README already in place as well. 💪

Just a few more changes to get this milestone approved. They can be seen in the comments below:

Status: Changes Required ♻️

NB: In this milestone, you are required to only **mock** the basic flow of the game. No game logic (e.g. checking for a winner) is required.

Please request for another review after implementing the changes.

Happy Coding 🖥️ 😃

You can contact me on slack (Chris Amanor) for any clarification.

2020-10-01 17:06 UTC, krys2fa commented on bin/main.rb
> +  board[index] = currentPlayersToken
- [ ] [REQUIRED] The game ends abruptly when a position is chosen. It should display the board after the selection and repeat all actions for the next player. Let's work on this.
<img width="726" alt="Screen Shot 2020-10-01 at 4 51 30 PM" src="https://user-images.githubusercontent.com/18187039/94840295-ba313000-0407-11eb-9419-89cbcb022cb9.png">

2020-10-01 17:10 UTC, krys2fa commented on bin/main.rb
> +    puts "Invalid token, please select 'X' or 'O'"
- [ ] [REQUIRED] Please take another look at the implementation for checking for a valid token. It results in an endless loop when an invalid token is chosen as shown below.
<img width="597" alt="Screen Shot 2020-10-01 at 4 48 50 PM" src="https://user-images.githubusercontent.com/18187039/94840037-5870c600-0407-11eb-9176-c8087f74d6b4.png">

2020-10-02 16:46 UTC, krys2fa requested changes
Nicely done @emmanuellekamwa and @enkog 👏

You made all the changes asked for in the previous review. 💪

Just **two** more changes to get this milestone approved. They can be seen in the comments:

Status: Changes Required ♻️

**NB:** In this milestone, you are required to only mock the basic flow of the game. No game logic (like checking for a winner) is required.

Please request for another review after implementing the changes.

Happy Coding 🖥️ 😃

You can contact me on slack (Chris Amanor) for any clarification.

2020-10-02 16:46 UTC, krys2fa commented on bin/main.rb
> +# which will return the next player name whose turn it is to play.
- [ ] [REQUIRED] The game should repeat all actions for the next player's move.
This should be implemented in this milestone.

2020-10-02 16:46 UTC, krys2fa commented on bin/main.rb
> +# Display gameboard with the available positions
- [ ] [REQUIRED] The game should display the board after the player move (without computing which spots on the board are taken).
This should be implemented in this milestone.

2020-10-05 05:28 UTC, tirthajyoti-ghosh requested changes
# Changes required 🛑 

## Impressive progress so far 💪! Thanks for making all the changes 👏.

### However, we need to work on some changes before we can merge.

Right now, the game stops right after tokens are assigned to the players. Have a look at this 👇 

![image](https://user-images.githubusercontent.com/57726348/95043151-9a488780-06f9-11eb-9da5-07c4234b7812.png)

This means that the `while` loop on line 42 is not getting executed. Please investigate this further and fix it.

Your project looks absolutely fantastic. Just make these changes and apply for another code review.

Happy coding 👨‍💻 

*Need help? Shoot me a message on Slack - [@Ghosh](https://app.slack.com/client/T47CT8XPG/DRDM6LAQN/user_profile/URB1MHXK6)*
<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

2020-10-05 11:31 UTC, expjazz approved these changes
## Status: Project Approved :green_circle: 

Great job team :clap: 

You implemented all the requested changes. Kudos for writing  the readme, even if it was not requested :1st_place_medal: 

Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-10-05 12:03 UTC, merged