Milestone 3 : Game Logic
enkog/Tic-Tac-Toe pull request #5
Opened 2020-10-07 10:25 UTC by emmanuellekamwa

Tic-Tac-Toe milestone 3: Game Logic
In this milestone, we:
-used classes to encapsulate the different parts of the game logic

2020-10-07 11:58 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello,

Thank you for the job done so far
However, there are some missing requirement and/or unexpected behavior

1. There is a turn
```rb
alice's Turn (X)
 X  | 2  | 3
-------------
 4  | O  | 6
-------------
 7  | 8  | 9
Enter a position: 
2
 X  | X  | 3
-------------
 4  | O  | 6
-------------
 7  | 8  | 9
bob's Turn (O)
 X  | X  | 3
-------------
 4  | O  | 6
-------------
 7  | 8  | 9
Enter a position: 
3
 X  | X  | O
-------------
 4  | O  | 6
-------------
 7  | 8  | 9
alice's Turn (X)
 X  | X  | O
-------------
 4  | O  | 6
-------------
 7  | 8  | 9
Enter a position: 
4
 X  | X  | O
-------------
 X  | O  | 6
-------------
 7  | 8  | 9
There is a tie
```
The result is a tie when is not one. Kindly fix that
Same thing here
```rb
bob's Turn (O)
 1  | X  | X
-------------
 4  | O  | 6
-------------
 7  | 8  | 9
Enter a position: 
1
 O  | X  | X
-------------
 4  | O  | 6
-------------
 7  | 8  | 9
alice's Turn (X)
 O  | X  | X
-------------
 4  | O  | 6
-------------
 7  | 8  | 9
Enter a position: 
6
 O  | X  | X
-------------
 4  | O  | X
-------------
 7  | 8  | 9
There is a tie
```

2. There are some issues during the OOP implementation of your game. Kindly read the comments left below to know more about them

**Please, keep in mind that every code into the `lib` folder must be written in such a way that any other developer can use them to as a library to build a Tic-Tac-Toe game with a GUI or a Web application**
The code into the `lib` folder must be independent as much as possible from the user interface, any kind of user interface

Kindly make the suggested changes and submit a new code review request
Thanks

Mael FOSSO

2020-10-07 11:58 UTC, maelfosso commented on lib/game.rb
> +  end
No `puts/gets` in any classes into `lib` folder

2020-10-07 11:58 UTC, maelfosso commented on lib/game.rb
> +    puts "#{player_one.name}, Choose a token: 'X' or 'O'"
No puts/gets in any classes into lib folder

2020-10-07 11:58 UTC, maelfosso commented on lib/game.rb
> +  def valid_move(index, _board)
why `_board` as parameter? It's never used in that method

2020-10-07 11:58 UTC, maelfosso commented on lib/game.rb
> +  def check_winning(player, board, winning_combination)
Please, remove `winning_combination` in parameters.
Move the `WINNING_COMBINATION` into that `Game` class as a constant

2020-10-07 11:58 UTC, maelfosso commented on bin/main.rb
> +].freeze
Move it into the `Game` class as a constant

2020-10-07 11:58 UTC, maelfosso commented on bin/main.rb
> +board = %w[1 2 3 4 5 6 7 8 9]
move it into `Game` class as an attribute.
The Game cannot exist without a `board`. If we delete the board, the game doesn't have a reason to exist

2020-10-07 11:58 UTC, maelfosso commented on bin/main.rb
> +game_tokens = %w[X O]
Move it also. Because it is here to only be sent to `Game` class method in parameter

2020-10-07 11:58 UTC, maelfosso commented on lib/game.rb
> +  end
Move it into the `bin/main.rb` file

2020-10-07 11:58 UTC, maelfosso commented on lib/game.rb
> +    end
simply check is all the items in `board` are Numeric. That is
```rb
board.all?(Numeric)
```

2020-10-07 11:58 UTC, maelfosso commented on lib/game.rb
> +  end
Why that line? 
Why not simply instantiate it in `bin/main.rb`?
There is apparently no reason for that method in that class

2020-10-07 11:58 UTC, maelfosso commented on bin/main.rb
> +  current_player.move_count += 1
Move it into the `Game` class wrapped into a method called for example `update_board`

2020-10-09 10:03 UTC, peterrobert requested changes
### CHANGES REQUIRED :recycle: :red_circle: 
### HELLO :wave: GOOD WORK SO FAR. GREAT WORK MAKING THE CHANGES AS REQUESTED BY THE PREVIOUS TSE :clap: HOWEVER, THERE ARE A FEW MORE CHANGES TO BE MADE KINDLY FIX THE FOLLOWING.

- [ ]  The application does not exist/stop due to invalid input. it informs the player about it and asks for their move again. If a player tries to move in an occupied position your application is stopping and it is throwing the following error :arrow_down:  Kindly fix this

`
update_board': undefined method pred  for nil:NilClass
`

### kindly fix this. If you have any question kindly reach me on slack @peterrobert

### HAPPY CODING :computer:

2020-10-09 10:03 UTC, peterrobert commented on lib/game.rb
> +  end
### [OPTIONAL]

There should be no explicit return statement

2020-10-11 21:20 UTC, kitpao requested changes
# 👋 Hello @emmanuellekamwa and @enkog 

👍 I loved that you added the option for the players to select a symbol to play with "X or O" 🌟 
I also see that you tried to fix the previous TSE suggestion, but you still have a bug there, please check it below:

- [ ] It seems that any invalid position will be assigned to number 9 in your program, please fix this behavior: 
![image](https://user-images.githubusercontent.com/53256139/95690461-99be5e00-0bdd-11eb-9f1f-4261961a392a.png)

- [ ] **OPTIONAL** Currently, your program accepts 2 players with the same name, you could add a "2" to the name or ask for a new name to avoid this :)

### ♻️ Status: Your project requires some additional changes ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me in slack as @kitpao
##### 🌟  If you have feedback about my reviews I would appreciate if can leave a recommendation in LinkedIn 💌 or let me know in Slack if you see improvements to be done 😛 

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-10-12 01:43 UTC, peterrobert requested changes
### CHANGES REQUIRED :recycle: :stop_sign: 
### HELLO :wave: GREAT PROGRESS SO FAR. YOUR PROJECT HAS IMPROVED BUT THERE ARE STILL SOME CHANGES TO BE DONE. KINDLY WORK ON THE FOLLOWING :arrow_down: 

- [ ] When the game starts, it should show aboard in order for the player to know where exactly he should select. Kindly check on this :arrow_down: 

![add board](https://user-images.githubusercontent.com/32361963/95696532-2a2f8980-0c44-11eb-8240-15f683660648.png)

- [ ] Great work the game does not stop when the same position is selected more than once. :+1:  However the game is not informing us that the position has already been selected. Kindly you need to add a message to inform us and asks the player to select another position:arrow_down:  

![samePos](https://user-images.githubusercontent.com/32361963/95696708-d8d3ca00-0c44-11eb-8ba7-36d776009f81.png)

### if you have any question concerning the review kindly reach me on slack @peterrobert 

### HAPPY CODING :computer:

2020-10-12 06:30 UTC, peterrobert approved these changes
### APPROVED :+1: :100: 
### VERY NICE WORK MAKING THE CHANGES :+1: ITS A GO FOR ME :+1: 
### ON TO THE NEXT PROJECT AND HAPPY CODING

2020-10-12 08:00 UTC, merged